services:
    - type: web
      name: laravel-app
      env: php
      plan: free
      buildCommand: |
          curl -sS https://getcomposer.org/installer | php &&
          php composer.phar install --no-dev --optimize-autoloader &&
          php artisan config:cache &&
          php artisan route:cache &&
          php artisan view:cache
      startCommand: php artisan serve --host 0.0.0.0 --port $PORT
      envVars:
          - key: APP_ENV
            value: production
          - key: APP_DEBUG
            value: false
          - key: APP_KEY
            value: base64:YOUR_APP_KEY
          - key: APP_URL
            value: https://your-app-name.onrender.com
          - key: DB_CONNECTION
            value: mysql
          - key: DB_HOST
            value: laravel-test-shashwatpandey100-7b72.l.aivencloud.com
          - key: DB_PORT
            value: 24346
          - key: DB_DATABASE
            value: defaultdb
          - key: DB_USERNAME
            value: avnadmin
          - key: DB_PASSWORD
            value: AVNS_L9NEeBGKKh3NXPZ5tAW
